// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JQ4tiRR051ExK_W8KdYqdnCpFKDy75M',
    appId: '1:15024072966:android:91a75c02e7d3ce3fad9687',
    messagingSenderId: '15024072966',
    projectId: 'gdgoc-hackathon-2026-490617',
    storageBucket: 'gdgoc-hackathon-2026-490617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrGBcYOa5LZmKdKRmpzfYPhE1V0e4_jE',
    appId: '1:15024072966:ios:7f2f0513daf9290fad9687',
    messagingSenderId: '15024072966',
    projectId: 'gdgoc-hackathon-2026-490617',
    storageBucket: 'gdgoc-hackathon-2026-490617.firebasestorage.app',
    androidClientId: '15024072966-36u1v0qmn60fujl0ccsui2aqal40k7f5.apps.googleusercontent.com',
    iosClientId: '15024072966-8rjbdgk2lm8ob44nebdm886v35h43r6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdgocHackathon2026',
  );
}
